### PR TITLE
Multiple sorting

### PR DESCRIPTION
**Pull request by thedrow**
This PR enabled sorting by multiple values.

[Review on Reviewable](https://reviewable.io/reviews/alex/django-filter/204)

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @thedrow.

Some thoughts:

1. This seems a good thing to support — but it would be nice to keep the single field version working as is. I'm not really a fan of this syntax for what I take to be the most common use-case:

        f = F({'o': ('-username',)}, queryset=self.qs)

Flip side is that we're changing a lot of tests to support the additional feature. 
2. So, how do we support BOTH the old usage and the new? (i.e. by converting to an iterable behind the scenes.)

**Comment by thedrow** [comment]
We can convert to an iterable behind the scenes and declare it as deprecated (or keep supporting it).

**Comment by carltongibson** [comment]
My first thought is to keep supporting it. 

A single ordering field strikes me as the most common case — I'd guess by a long margin — so I'd like the API there to be as friendly as possible. Sound fair?

**Comment by thedrow** [comment]
The tests are using a dict but usually a filterset will have a QueryDict which has getlist().
I guess that if you use a filterset directly you will use a querydict and then we have no problem.
I think that keeping the API backwards compatitable in this case is not worth the extra branching.
If you want to keep this I think we should be deprecating it.

**Comment by carltongibson** [comment]
Right. @thedrow Sorry for the delay in responding — busy as ever.

I was previously confused between the internal change made here and the user-facing declaration of the `order_by` Meta attribute — you're not suggesting any of the latter. 

As such, I'm happy to go with a break — plus a temporary check and helpful error message perhaps. 

Can you (re-)apply your cleaner version of the code? (Again, sorry for my misunderstanding.)

Can you add a new section to CHANGES.rst and call this out as a breaking (internal) change?

Also can you add a small note about multiple sorting being supported to the relevant section in docs/usage.txt?

Finally, just for my sanity, can you add a test mixing directions? Something like: 

    {'o': ('status', '-username')}

... since that should work too. 

Thanks!

**Comment by carltongibson** [comment]
Oh. One thing that did occur to me was the change in UI. (`Choice...` to `MultipleChoice...`) Do we upset anyone there? Is it worth the pain adding flexibility?

**Comment by thedrow** [comment]
I think that being able to sort by multiple fields is worth the trouble.
Most of us don't use django-filter to generate the forms but use it with DRF.

**Comment by carltongibson** [comment]
@thedrow Right! But there's also a lot of people (many of them newish to Django) using DF (cough) _the old-fashioned way_. 

I think we should default to `Choice...` for the UI — just for backwards compatibility. 

[This section in the docs](https://django-filter.readthedocs.org/en/latest/usage.html#overriding-filterset-methods) needs reworking to explain how to change to `MultipleChoice...` — and I guess how to override `get_order_by` to actually disable multiple sort — if that's your thing.

Open to discussion but my first preference would be that `get_ordering_field` take a `field_type=forms.ChoiceField` param — so switching would involve a subclass. (Really happy to see a nicer solution.)

**Comment by thedrow** [comment]
Using a ChoiceField will disable multiple sorting completely.

**Comment by carltongibson** [comment]
> ... 

Grrrr. OK. Then lets change the default. Grrrr.

We're basically reversing the situation as it is now. [This section in the docs](https://django-filter.readthedocs.org/en/latest/usage.html#overriding-filterset-methods) needs to explain how to return to single ordering — and restore the current behaviour — rather than, as now, how to implement this change yourself.

**Comment by thedrow** [comment]
Should I revert https://github.com/thedrow/django-filter/commit/0a1769aa5240549956f9787028e1451ada31890b then?

**Comment by carltongibson** [comment]
Yeah :-) — sorry for the confusion there.

**Comment by thedrow** [comment]
I'm really sorry it took me so long to get to this.
Can you please merge?

**Comment by carltongibson** [comment]
@thedrow We still have the docs issue — they currently say that multiple sorting is not supported out of the box and provide an example of how to implement it. (I gave the link above.)

I'm going to sit down with the documentation soon enough and I can review then but if you're desperate to have it merged that needs addressing.

**Comment by carltongibson** [comment]
I'm going to close this in favour of the [existing, documented method of supporting multiple ordering](https://django-filter.readthedocs.org/en/latest/usage.html#overriding-filterset-methods). It might be something we can come back to but it's not high priority for now.

**Comment by thedrow** [comment]
Sorry, I had no time to contribute documentation to this feature.
Other than that, any other reason to reject this feature?

**Comment by carltongibson** [comment]
@thedrow No problem. 

> Other than that, any other reason to reject this feature?

Just scope really: not worth the breaking change at this point. 

(My goal is to make progress on the docs and tidy up the edges. Once there I'd happily revisit this.)

**Pull request closed without merging**
