### PR TITLE
Add lookup_type filter overrides

### LINKED ISSUE #273: 'field': ['isnull'] not working with django-filter 0.10.0 / Django 1.8 / DRF 3.1.2
I am trying to set up a `field__isnull=True/False` filter but I'm can't get it to work with django-filter 0.10.0 / Django 1.8 / DRF 3.1.2.

Code that is _not_ working:
```
class MyFilter(django_filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {
            'field': ['isnull'],
        }
```

`GET /api/my_model/?field__isnull=True` -> returns an empty array, no SQL is being ran according to Django's shell.

Code that did work:

```
class MyFilter(django_filters.FilterSet):
    field__isnull = django_filters.BooleanFilter(action=lambda q, v: q.filter(field__isnull=v))
    class Meta:
        model = MyModel
        fields = {
        ...some other field declarations
        }
```

`GET /api/my_model/?field__isnull=True` does what it is supposed to, SQL looks OK.

EDIT: the field I'm working with is a MySQL DateTimeField that is usually `null` but sometimes has a DateTime.

### PR DESCRIPTION
**Pull request by rpkilby**
Fixes #273 as an example

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. At first glance, not a bad idea. 

1. It would need docs. 
2. Would we want class level overrides? 
3. I'm not, just by looking at it, convinced that the behaviour would always be correct. (The example that comes to mind it passing a list as the lookup type.) Perhaps it's fine but I'd like the tests to make that obvious.

**Comment by rpkilby** [comment]
> Would we want class level overrides?

It would make sense - a useful case would be to to override the isnull widget to use radio buttons. That said, I have a feeling that some overrides will be more involved and require overriding `lookup_type_overrides`. For example, an override for an `__in` lookup may require the underlying char or int field type for an array filter factory or something.

> I'm not, just by looking at it, convinced that the behaviour would always be correct. (The example that comes to mind it passing a list as the lookup type.) Perhaps it's fine but I'd like the tests to make that obvious. 

Not sure I follow the example - Do you mean passing a list of lookup types to the `lookup_type` parameter of `filter_for_field` (and subsequently `filter_for_lookup_type`)? Is a list a valid there?

**Comment by carltongibson** [comment]
I mean passing a list to the [`lookup_type` kwarg](http://django-filter.readthedocs.org/en/latest/ref/filters.html#lookup-type) of a `Filter` instance

**Comment by rpkilby** [comment]
That makes more sense - didn't know that was a feature. 

Especially given the class level overrides, I think it makes sense to only affect filters generated from the meta fields attribute.

A few more thoughts on that:
- `lookup_type_overrides` operates similarly to `filter_overrides`. The latter option only affects how filters are generated from `FilterSet.Meta.fields` - declared filter instances aren't affected by the override.
- I don't know how to cleanly pass the override to the filters. The overrides are associated with the `FilterSet` class definition, however the `Filter`s are already initialized by this point. The FilterSet could set the overrides on the filters during it's class creation, but this seems like it would increase coupling between the two. Filter behavior would change when associated with a FilterSet. The code would look something like...
```python
class FilterSetMetaclass(type):
    def __new__(cls, name, bases, attrs):
        ...
        # set the overrides on the filters
        for filter_ in filters.values():
            filter_.filter_overrides = new_class.filter_overrides
            filter_.lookup_type_overrides = new_class.lookup_type_overrides
        new_class.declared_filters = declared_filters
        new_class.base_filters = filters
        return new_class
```
- The `LookupTypeField` and widget would be more complex, possibly including javascript to switch between different inputs. ie, the base widget is a number input, but would need a dropdown/radio buttons for the isnull lookup.

**Comment by carltongibson** [comment]
And it's here that I begin to think that asking users to declare their filters explicitly IS the best option...

— I'm happy to review what you come up with but if it's too complex I'm ultimately going to say No

**Comment by rpkilby** [comment]
Hey. I think I'm on the wrong page here. At this point, I'm suggesting to submit the PR somewhere close to its current state, which includes the added docs and class level overrides.

In my previous comment, I was trying to clarify why I *don't* think that it makes sense to have the lookup_type overrides affect declared filter instances. It would result in something ugly and complex, as well as be inconsistent with how `filter_overrides` behaves.

At this point, is there anything that needs to be clarified in docs/tests? What correctness issues need to be sorted out?

**Comment by rpkilby** [comment]
Closing for now as this isn't going to work well with chained lookup expressions in Django 1.9.
e.g, `.filter(some_datetime__hour__gte=4)`. I'll take another stab at this at some point.

**Comment by carltongibson** [comment]
Ok thanks. Happy to discuss ideas if that helps.

**Pull request closed without merging**
