### PR TITLE
use `count(*)` instead of `select * from table`;

### PR DESCRIPTION
**Pull request by yrik**

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. This seems reasonable.

Can I just ask, how come you found it? Just browsing the source or was there an issue?

**Comment by yrik** [comment]
It was easy to notice on 3M database when page crashed with 504 error. Had to patch django to log queries before execution. Found that it was caused by this query.

**Comment by carltongibson** [comment]
Nice. 😀

We'll have this then. 

I'm prepping a new release. It won't be for a bit though (i.e. I hope next week but it's possible it could slip), so you may want to deploy off of `develop` in the meantime.

**Comment by yrik** [comment]
Thanks

**Pull request merged**
