### PR TITLE
Range filters allow zero values.

### PR DESCRIPTION
**Pull request by JamesBradbury-Abide**
Extended tests for NumericRangeFilter and RangeFilter to include zero values.

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. Good. Thanks for this @JamesBradbury-Abide! 👍

**Comment by JamesBradbury-Abide** [comment]
Thanks @carltongibson. Do you know when this is likely to be packaged and available to pip install? Just want to know if we should use our forked one instead for the time being.

**Comment by carltongibson** [comment]
Hi @JamesBradbury-Abide — I haven't quite got time to wrap up everything I want to this week, so I'm thinking I'll just push a quick release with what's merged thus far. (Either this evening or tomorrow)

**Comment by carltongibson** [comment]
Follow the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for notices.

**Pull request merged**
