### PR TITLE
Provide a means of avoiding distinct() on MultipleChoiceFilter

### PR DESCRIPTION
**Pull request by JonPeel**
When using the MultipleChoiceFilter (or anything derived from it) we were having issues with the performance of queries whenever they included a superfluous distinct() call (not at all needed in our case, the filter doesn't add duplication).  Seems this is easily avoided in the base Filter class but not in the MultipleChoiceFilter.  Changed: Adding the same self.distinct check as seen in Filter and defaulting to 'distinct=True' on the MultipleChoiceFilter for backward compatibility sake.

Generally a bit bemused by the `distinct` tangle we have here;  deferring all logic on whether distinct() is needed would surely sits better with whatever is responsible for running the final query?

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @JonPeel — Thanks. This looks great. 

The Travis build doesn't appear to have run — I'll have a look and see if I can work that out in the morning.

**Comment by JonPeel** [comment]
Pull request updated with similar changed to honour the exclude=True flag provided by the base Filter class.

I've skipped DateRangeFilter as dealing with the class level lambda's is an interface change I don't want to get involved in. Everything else is rather straightforward.

Please let me know what changes, if any, would be required to merge

**Comment by vperron** [comment]
Has this been read again yet ? Would be very useful to us !

**Comment by carltongibson** [comment]
It's been read. I'll get to it. 

Sorry for the delay — it's a question of time. We're currently at 17 issues and 15 PRs — down from >100 and ≈40 when I took on the project — so we're Getting There™

**Comment by vperron** [comment]
Sure :) Was just an inquiry. Impressive work by the way...

**Comment by carltongibson** [comment]
I'm closing this in favour of #278 — that just brings this up to the latest develop. (Having not got to it sooner I felt bad asking you to update.)

Thanks for the work here @JonPeel! Awesome!

**Comment by JonPeel** [comment]
@carltongibson - no worries, thanks for the update / merge.

**Pull request closed without merging**
