### PR TITLE
add UUIDField from #294

### PR DESCRIPTION
**Pull request by thenewguy**
#243 #294

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. Thanks for this. 

1. Can you fix the failing tests on Python 3. (You need to use `as` rather than `,` in the `except` expression.)
2. Can you add an appropriate entry to the Filter Reference Docs.

**Comment by thenewguy** [comment]
Sure... old habits die hard and I am working on a py2 project at the moment. I tried to wait for the tests to run but they were queued for a very long time.

**Comment by thenewguy** [comment]
Hrm, these failures are odd enough... I'll adjust the reference https://travis-ci.org/alex/django-filter/jobs/79552463, https://travis-ci.org/alex/django-filter/jobs/79552465, https://travis-ci.org/alex/django-filter/jobs/79552468

**Comment by rafaelcaricio** [comment]
@thenewguy @carltongibson anything I can do to get this merged? any code changes expected? docs?

**Comment by thenewguy** [comment]
@rafaelcaricio I believe it is ready for checkin

**Comment by carltongibson** [comment]
Oops. Sorry for the delay here. I had it in mind that the build was still failing. Will review over the weekend. 

Looks like we're edging towards a new release.

**Comment by rafaelcaricio** [comment]
Cool! Thank you.

**Pull request merged**
