### PR TITLE
Date/time range filters

### PR DESCRIPTION
**Pull request by bogdal**
This adds two new filters `TimeRangeFilter` and `DateFromToRangeFilter`.
The second one can be used with both model fields `DateTimeField` and `DateField`.

### CODE REVIEW

**Comment by bogdal** [comment]
Hi! Is there a chance to see the above filters as a part of this package?
Cheers!

**Comment by carltongibson** [comment]
Hi @bogdal — Yes. Definitely. 

Sorry for the delay in processing this: Time for OSS, as ever, is scarce. Can you just update to latest develop and I'll merge it in. (I'm planning a new release soon-ish but I want to process a few more issues first.)

**Comment by SeanHayes** [comment]
@carltongibson Can this be merged now? Looks like it was updated to the latest develop and can be automatically merged now.

**Comment by carltongibson** [comment]
Hi, yes. I'll pull this in over the weekend. Sorry for having it hanging so long; I've had ≈0 time. I pushed a release yesterday to cover a bug with Django v1.8. The next release will bring in the unmerged new features.

**Comment by rjschave** [comment]
I'm having trouble figuring out how to render fields on a form that use the DateFromToRangeFilter (or any Range filter for that matter).  Do you have an example of how that works?

**Pull request merged**
